### ISSUE TITLE
Hint for Single-Character Words

### ISSUE THREAD

**Issue by Thomas-siby** [jobeljohny/hangman#7]
In English, there are only two One-letter words; A & I. But in the case of movies there are plenty with numerals or even special characters such as 

- Romeo + Juliet
- WALL·E
- 61*
- $5 a Day
- 9½ Weeks

If the user had to randomly guess whether the Single-Character word is a Alphabet, Numeral  or a Special Character then it would take up a lot of guesses. Only if there was a hint given to the user to know that its one of Alphabet, Numeral  or a Special Character , then it would have been easier for the user to track down the movie name.

**Comment by jobeljohny** [comment]
added an icon if numbers are present in the movies. also the V-Keyboard does not show numbers row if they aren't present
